// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apuntes: [
    "home",
    {
      "Lecciones": [{
        type: 'autogenerated',
        dirName: 'lecciones', // '.' means the current docs folder
      }]
    },
    {
      "Preguntas": [{
        type: 'autogenerated',
        dirName: 'preguntas', // '.' means the current docs folder
      }]
    },
    {
      "Verbos": [{
        type: 'autogenerated',
        dirName: 'verbos', // '.' means the current docs folder
      }]
    },
    {
      "Vocabulario": [{
        type: 'autogenerated',
        dirName: 'vocabulario', // '.' means the current docs folder
      }]
    },
  ]
};

export default sidebars;
