// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apuntes: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
  ]
};

export default sidebars;
